- name: Generate DRS and local publication
  hosts: gateway
  tasks:
    - name: Copy config files
      copy:
        src: "{{ item }}"
        dest: /esg/config/{{ item }}
      with_items:
        - esgf_idp_static.xml
        - esgf_known_providers.xml
        - esgf_policies_local.xml
        - esgf_ats_static.xml

    - name: Add hostcert to grid-security
      shell: cp /etc/certs/hostcert.pem /etc/grid-security/certificates/$(openssl x509 -hash -noout < /etc/certs/hostcert.pem).0

    # Replicate SQL database
    - name: Install pyexpect
      pip:
        name: pexpect
        executable: "/usr/local/conda/envs/esgf-pub/bin/pip"

    - name: Delete existing database sessions
      expect:
        command: psql -c "select pg_terminate_backend(procpid) from pg_stat_activity where datname = 'esgcet'" esgcet dbsuper
        responses:
          Password: "CHANGEME"
      environment:
        PYTHONPATH: /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/
      ignore_errors: True

    - name: Delete existing database
      expect:
        command: dropdb -U dbsuper esgcet
        responses:
          Password: "CHANGEME"
      environment:
        PYTHONPATH: /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/

    - name: Create esgcet database
      expect:
        command: createdb -U dbsuper esgcet
        responses:
          Password: "CHANGEME"
      environment:
        PYTHONPATH: /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/

    - name: Import postgres database
      expect:
        command: bash -c 'psql --username dbsuper esgcet < /root/esgf-test/db.sql'
        responses:
          Password: "CHANGEME"
      environment:
        PYTHONPATH: /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/
        
    # DRS and mapfile
    - name: Copy sftlf.nc to /esg/data/test
      copy: src=sftlf.nc dest=/esg/data/test/sftlf.nc

    - name: mkdir /esg/data/drs
      file:
        state: directory
        path: /esg/data/drs

    - name: Copy esg.test.ini
      copy: src=esg.test.ini dest=/esg/config/esgcet/esg.test.ini

    - name: esgdrs
      command: esgdrs {{ item }} --project test --symlink  --set-value project=Test /esg/data/test/
      args:
        chdir: /esg/data/drs
      with_items: [list, tree, todo, upgrade]
      tags: [never, drs]

    - name: esgmapfile
      command: esgmapfile --project test Test/
      args:
        chdir: /esg/data/drs
      tags: [never, drs]

    - name: Allow access from everywhere to COG
      replace:
        path: /usr/local/cog/cog_install/settings.py
        regexp: ALLOWED_HOSTS(.*)
        replace: ALLOWED_HOSTS = ['*']
      tags: asdf
